In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install pyarrow fastparquet duckdb -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 22.3 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import duckdb
import os

In [ ]:
months = [
    "2025-01",
    "2025-02",
    "2025-03",
    "2025-04",
    "2025-05",
    "2025-06"
]

base_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/"

In [ ]:
raw_path = "/content/drive/MyDrive/RDV_Project/raw_data"

os.makedirs(raw_path, exist_ok=True)

print("Folder siap:", raw_path)

Folder siap: /content/drive/MyDrive/RDV_Project/raw_data

In [ ]:
import urllib.request

for month in months:
    file_name = f"yellow_tripdata_{month}.parquet"
    url = base_url + file_name

    save_path = os.path.join(raw_path, file_name)

    if not os.path.exists(save_path):
        print(f"Downloading {file_name}...")
        urllib.request.urlretrieve(url, save_path)
        print(f"Saved: {save_path}")
    else:
        print(f"{file_name} already exists")

Downloading yellow_tripdata_2025-01.parquet...
Saved: /content/drive/MyDrive/RDV_Project/raw_data/yellow_tripdata_2025-01.parquet
Downloading yellow_tripdata_2025-02.parquet...
Saved: /content/drive/MyDrive/RDV_Project/raw_data/yellow_tripdata_2025-02.parquet
Downloading yellow_tripdata_2025-03.parquet...
Saved: /content/drive/MyDrive/RDV_Project/raw_data/yellow_tripdata_2025-03.parquet
Downloading yellow_tripdata_2025-04.parquet...
Saved: /content/drive/MyDrive/RDV_Project/raw_data/yellow_tripdata_2025-04.parquet
Downloading yellow_tripdata_2025-05.parquet...
Saved: /content/drive/MyDrive/RDV_Project/raw_data/yellow_tripdata_2025-05.parquet
Downloading yellow_tripdata_2025-06.parquet...
Saved: /content/drive/MyDrive/RDV_Project/raw_data/yellow_tripdata_2025-06.parquet

In [ ]:
sample_file = os.path.join(
    raw_path,
    "yellow_tripdata_2025-01.parquet"
)

df = pd.read_parquet(sample_file)

df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [ ]:
selected_columns = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "PULocationID",
    "DOLocationID",
    "trip_distance",
    "fare_amount"
]

In [ ]:
all_data = []

for month in months:
    file_path = os.path.join(
        raw_path,
        f"yellow_tripdata_{month}.parquet"
    )

    df = pd.read_parquet(
        file_path,
        columns=selected_columns
    )

    df["month"] = month

    all_data.append(df)

combined_df = pd.concat(
    all_data,
    ignore_index=True
)

print(combined_df.shape)
combined_df.head()

(24083384, 7)

,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,trip_distance,fare_amount,month
0,2025-01-01 00:18:38,2025-01-01 00:26:59,229,237,1.60,10.0,2025-01
1,2025-01-01 00:32:40,2025-01-01 00:35:13,236,237,0.50,5.1,2025-01
2,2025-01-01 00:44:04,2025-01-01 00:46:01,141,141,0.60,5.1,2025-01
3,2025-01-01 00:14:27,2025-01-01 00:20:01,244,244,0.52,7.2,2025-01
4,2025-01-01 00:21:34,2025-01-01 00:25:06,244,116,0.66,5.8,2025-01

In [ ]:
output_path = "/content/drive/MyDrive/RDV_Project/processed_data"

os.makedirs(output_path, exist_ok=True)

combined_df.to_parquet(
    f"{output_path}/taxi_raw_ingested.parquet",
    index=False
)

print("Raw ingested data saved")

Raw ingested data saved